name: quickobs
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.9.2+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  convert: ^3.0.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  form_builder_validators: ^8.3.0
  http: ^0.13.5
  shared_preferences: ^2.0.15
  very_good_analysis: ^3.1.0
  yaru: ^0.4.1
  yaru_icons: ^0.2.4
  yaru_widgets: ^1.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
